Vagrant.configure("2") do |config|

    config.vm.define "nlesageS" do |server|

        server.vm.box = "ubuntu/mantic64"
        server.vm.hostname = "nlesageS"
        server.vm.synced_folder "./confs", "/vagrant", type: "virtualbox"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "nlesageS"]
            v.memory = 2048
            v.cpus = 1
        end

        server.vm.provision "shell", path: "./scripts/setup.sh"
    end
end
