# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.define "nlesageS" do |server|
    server.vm.box = "ubuntu/mantic64"
    server.vm.hostname = "nlesageS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "nlesageS"]
      v.memory = 1024
      v.cpus = 1
    end

    server.vm.provision "shell", inline: <<-SHELL
      sudo ufw disable
      sudo ufw allow 6443/tcp
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode=644 --node-ip 192.168.56.110 --advertise-address 192.168.56.255" sh -s -
      
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
      sudo sed -i 's/127.0.0.1/192.168.56.110/g' /etc/rancher/k3s/k3s.yaml
      sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/k3s.yaml
      sed -i 's/127.0.0.1/192.168.56.110/g' /vagrant/k3s.yaml

      apt update
      apt install net-tools

      sudo ip link add eth1 type dummy && sudo ip addr add 192.168.56.110/24 dev eth1 && sudo ip link set eth1 up
    SHELL
  end

  config.vm.define "nlesageSW" do |worker|
    worker.vm.box = "ubuntu/mantic64"
    worker.vm.hostname = "nlesageSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "nlesageSW"]
      v.memory = 1024
      v.cpus = 1
    end

    worker.vm.provision "shell", inline: <<-SHELL
      sudo ufw disable
      export K3S_TOKEN=$(cat /vagrant/node-token)
      echo $K3S_TOKEN
      # curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://192.168.56.110:6443 --node-ip 192.168.56.111" K3S_TOKEN=${K3S_TOKEN} sh -s -

      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --node-ip 192.168.56.111" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=${K3S_TOKEN} sh -s -
      
      apt update
      apt install net-tools

      sudo ip link add eth1 type dummy && sudo ip addr add 192.168.56.111/24 dev eth1 && sudo ip link set eth1 up
    SHELL
  end
end
